[package]
name = "security-token-program"
version.workspace = true
description.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "security_token_program"

[features]
default = []
no-entrypoint = []

[dependencies]
solana-program = { workspace = true }
solana-system-interface = { workspace = true }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
spl-associated-token-account = { workspace = true }
spl-pod = { workspace = true }
bytemuck = { workspace = true }
thiserror = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.solana]
program-id = "11111111111111111111111111111112"
